with CTE AS (

select 

TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_STARTED_AT,
{{get_season('STARTED_AT')}} AS STATION_OF_YEAR,
{{day_type('STARTED_AT')}} as DAYTYPE

from {{ ref('stg_bike') }}
    WHERE STARTED_AT != 'started_at'
)

SELECT * FROM CTE 

