with TRIPS as (

select 
RIDE_ID,
DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
START_STATIO_ID as START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECOUNDS


    from {{ ref('stg_bike') }}



)

select * from TRIPS
